export default Object.freeze({
    WELCOME: 'Welcome',
    HOME: "Home",
    AUTH: 'Auth',
    ACCOUNT: 'Account',
    CREATE_GROUP: 'Create Group',
    LOGIN: 'Log In Account',
    EMAIL_LOGIN: 'Email Login',
    EMAIL_VERIFICATION_RESEND: 'Email Resend',
    FORGOT_PASSWORD: 'Forgot Password',
    RESET_PASSWORD: 'Reset Password',
    VERIFICATION: 'Verification',
    CHOOSE_TEAM: 'Choose Team',
    FEED_STACK: 'FeedStack',
    FEED: 'Feed',
    REGISTER: 'Register',
    SETTINGS_STACK: 'SettingsStack',
    SETTINGS: 'Settings',
    ABOUT: 'About',
    TERMS: 'Terms & Conditions',
    PRIVACY: 'Privacy Policy',
    REQUEST_VERIFICATION: 'Request Verification',
    REQUEST_VERIFICATION_REJECTED: 'Request Rejected',
    PROFILE: 'Profile',
    EDIT_PROFILE: 'Edit Profile',
    FOLLOWERS: 'Followers',
    ROOM: 'Room',
    SEND_FEEDBACK: 'Send Feedback',
    FOLLOW_AND_INVITE: 'Follow and Invite',
    PEOPLE_AND_ROOMS: 'People & Rooms',
    SEARCH_STACK: 'SearchStack',
    MATCH_STACK: 'MatchStack',
    MATCH_DETAILS: 'MatchDetails',
    TEAM_STACK: 'TeamStack',
    TEAM_DETAILS: 'TeamDetails',
    TEAM_COMMUNITY: 'TeamCommunity',
    MEDIA_STACK: 'MediaStack',
    COMMENTS: 'Comments',
    MEDIA_LIKES: 'MediaLikes',
    LIVE_ROOMS: 'LiveRooms',
    LIVE_MATCHES: 'LiveMatches',
    MATCH_RESULTS: 'MatchResults',
    COMPLETE_REGISTRATION: 'Complete Registration'
});
